version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
#    ports:
#      - 2181:2181
#      - 2888:2888
#      - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
#    ports:
#      - 9092:9092
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "19000:9000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Standard
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_AGENT_ENABLED=true
  mongo:
    image: "mongo:7.0.0"
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    ports:
      - "27017:27017"
    restart: always
  mongo-express:
    image: mongo-express
    ports:
      - 18081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ROOT_PASSWORD
    links:
      - mongo
    depends_on:
      - mongo
  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    ports:
      - 8083:8083
    links:
      - kafka
      - sqlserver
      - mongo
    depends_on:
      - kafka
      - sqlserver
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
    volumes:
      - ./etc/connector/mongodb-kafka-connect-mongodb-1.11.1:/kafka/connect/mongo-connector
  sqlserver-script-executor:
    image: mcr.microsoft.com/mssql-tools
    volumes:
      - ./etc/init/setup-sqlserver.sh:/setup-sqlserver.sh
      - ./etc/debezium-sqlserver-init/inventory.sql:/scripts/inventory.sql
    command: /bin/bash /setup-sqlserver.sh
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
    depends_on:
      - sqlserver
  setup-connectors:
    image: ubuntu
    volumes:
      - ./etc/init/setup-connectors.sh:/setup-connectors.sh
      - ./etc/connector:/connector
    command: /bin/bash /setup-connectors.sh
    environment:
      - MONGO_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - SA_PASSWORD=$SA_PASSWORD
    depends_on:
      - connect